version: "3.9"
services:
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: "tests"
      POSTGRES_USER: "testsuser"
      POSTGRES_PASSWORD: "testpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d/init.sql
      - tests-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  tests-data: